import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {openDatabase} from '../src/db.js';

test('symbol search prioritizes ticker and returns cached quote',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bourse-db-')),db=openDatabase(path.join(dir,'x.db'));db.upsertSymbols([{symbol:'فولاد',name:'فولاد مبارکه',lastPrice:3350},{symbol:'افولاد',name:'شرکت نمونه فولاد',lastPrice:10}]);const rows=db.searchSymbols('فولاد');assert.equal(rows[0].symbol,'فولاد');assert.equal(rows[0].lastPrice,3350);db.close();});
test('portfolio positions can be added, edited, summarized and deleted',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'portfolio-db-')),db=openDatabase(path.join(dir,'x.db'));db.upsertSymbols([{symbol:'فولاد',name:'فولاد مبارکه',lastPrice:3000,closePrice:2990}]);db.savePortfolioPosition({symbol:'فولاد',quantity:1000,avgPrice:2500,buyFeePct:.4,stopPrice:2300});assert.equal(db.portfolioPositions().length,1);assert.equal(db.portfolioPosition('فولاد').quantity,1000);db.savePortfolioPosition({symbol:'فولاد',quantity:1250,avgPrice:2600,buyFeePct:.5});assert.equal(db.portfolioPositions().length,1);assert.equal(db.portfolioPosition('فولاد').quantity,1250);assert.equal(db.portfolioPosition('فولاد').avg_price,2600);assert.equal(db.portfolioPosition('فولاد').buy_fee_pct,.5);assert.equal(db.portfolioPosition('فولاد').stop_price,2300);const overview=db.portfolioOverview();assert.equal(overview.summary.symbolCount,1);assert.equal(overview.summary.totalCurrentValueRial,3_750_000);assert.equal(overview.summary.totalCostRial,3_266_250);assert.equal(overview.summary.totalProfitRial,483_750);assert.equal(overview.positions[0].current_price,3000);assert.equal(db.deletePortfolioPosition('فولاد'),true);assert.equal(db.portfolioPosition('فولاد'),undefined);db.close();});
test('portfolio uses the newest stored candle when the market quote is stale',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'portfolio-fallback-')),db=openDatabase(path.join(dir,'x.db'));db.upsertSymbols([{symbol:'لبن',name:'لبنیات',lastPrice:10000,closePrice:9900,date:'1405/06/20'}]);db.upsertCandles('لبن',[{date:'1405/06/22',open:10800,high:11200,low:10700,close:11100,volume:1000}],'rahavard',1);db.savePortfolioPosition({symbol:'لبن',quantity:10,avgPrice:9000});const [position]=db.portfolioOverview().positions;assert.equal(position.current_price,11100);assert.equal(position.price_source,'rahavard');assert.equal(position.price_date,'1405/06/22');assert.equal(position.buy_fee_pct,1.262);db.close();});
test('delete monitor cascades its archived events',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bourse-db-')),db=openDatabase(path.join(dir,'x.db')),monitor=db.createMonitor({title:'x',symbol:'فولاد',inputMode:'text',sourceText:'قیمت بیشتر از 1',expression:{type:'rule',field:'lastPrice',operator:'gt',value:1},actionType:'BUY',quantity:1,proposedPrice:1,maxAmountToman:null,startAt:new Date().toISOString(),endAt:new Date(Date.now()+60000).toISOString(),intervalMinutes:1,cooldownMinutes:1});db.addEvent(monitor.id,'active',{state:'active'},null,true);assert.equal(db.recentEvents().length,1);db.deleteMonitor(monitor.id);assert.equal(db.recentEvents().length,0);db.close();});

test('updates and bulk deletes legacy and v2 monitoring without deleting archive',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bourse-edit-')),db=openDatabase(path.join(dir,'x.db')),input={title:'اول',symbol:'فولاد',inputMode:'builder',sourceText:'',expression:{type:'rule',field:'lastPrice',operator:'gt',value:1},actionType:'BUY',quantity:1,proposedPrice:1,maxAmountToman:null,startAt:new Date().toISOString(),endAt:new Date(Date.now()+60000).toISOString(),intervalMinutes:1,cooldownMinutes:1},monitor=db.createMonitor(input);assert.equal(db.updateMonitor(monitor.id,{...input,title:'ویرایش'}).title,'ویرایش');const archived=db.createMonitor(input);db.updateMonitorStatus(archived.id,'completed');const rule=db.createRuleV2({ruleId:'R',symbol:'فولاد',name:'قاعده',scope:'SYMBOL',severity:'WATCH',expression:{type:'condition',name:'PRICE_ABOVE',params:{value:1}},action:'ALERT',cooldownMinutes:1,intervalMinutes:1});assert.equal(db.updateRuleV2(rule.id,{...rule,name:'قاعده جدید',enabled:true}).name,'قاعده جدید');const removed=db.bulkDeleteMonitoring([],true);assert.equal(removed.total,2);assert.equal(db.listMonitors({archive:true}).length,1);assert.equal(db.listRulesV2().length,0);db.close();});

test('prunes legacy and v2 alert logs after three days',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'event-prune-')),db=openDatabase(path.join(dir,'x.db')),input={title:'هشدار',symbol:'فولاد',inputMode:'builder',sourceText:'',expression:{type:'rule',field:'lastPrice',operator:'gt',value:1},actionType:'ALERT',quantity:1,proposedPrice:1,maxAmountToman:null,startAt:new Date().toISOString(),endAt:new Date(Date.now()+60000).toISOString(),intervalMinutes:1,cooldownMinutes:1},monitor=db.createMonitor(input),rule=db.createRuleV2({ruleId:'PRUNE',symbol:'فولاد',name:'قاعده',scope:'SYMBOL',severity:'WATCH',expression:{type:'condition',name:'PRICE_ABOVE',params:{value:1}},action:'ALERT'});db.addEvent(monitor.id,'active',{ok:true},null,false);db.recordRuleResultV2(rule,{state:'active',evidence:[]},{current:{price:2},market:{},portfolio:null},false);const old=new Date(Date.now()-4*86400000).toISOString();db.raw.prepare('UPDATE monitor_events SET created_at=?').run(old);db.raw.prepare('UPDATE rule_events_v2 SET created_at=?').run(old);db.addEvent(monitor.id,'inactive',{ok:false},null,false);db.recordRuleResultV2(rule,{state:'inactive',evidence:[]},{current:{price:1},market:{},portfolio:null},false);db.prune(90,3);assert.equal(db.recentEvents().length,1);assert.equal(db.recentRuleEventsV2().length,1);db.close();});
