import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {openDatabase} from '../src/db.js';

test('symbol search prioritizes ticker and returns cached quote',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bourse-db-')),db=openDatabase(path.join(dir,'x.db'));db.upsertSymbols([{symbol:'فولاد',name:'فولاد مبارکه',lastPrice:3350},{symbol:'افولاد',name:'شرکت نمونه فولاد',lastPrice:10}]);const rows=db.searchSymbols('فولاد');assert.equal(rows[0].symbol,'فولاد');assert.equal(rows[0].lastPrice,3350);db.close();});
test('portfolio positions can be added, edited and deleted',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'portfolio-db-')),db=openDatabase(path.join(dir,'x.db'));db.savePortfolioPosition({symbol:'فولاد',quantity:1000,avgPrice:2500});assert.equal(db.portfolioPositions().length,1);assert.equal(db.portfolioPosition('فولاد').quantity,1000);db.savePortfolioPosition({symbol:'فولاد',quantity:1250,avgPrice:2600});assert.equal(db.portfolioPositions().length,1);assert.equal(db.portfolioPosition('فولاد').quantity,1250);assert.equal(db.portfolioPosition('فولاد').avg_price,2600);assert.equal(db.deletePortfolioPosition('فولاد'),true);assert.equal(db.portfolioPosition('فولاد'),undefined);db.close();});
test('delete monitor cascades its archived events',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bourse-db-')),db=openDatabase(path.join(dir,'x.db')),monitor=db.createMonitor({title:'x',symbol:'فولاد',inputMode:'text',sourceText:'قیمت بیشتر از 1',expression:{type:'rule',field:'lastPrice',operator:'gt',value:1},actionType:'BUY',quantity:1,proposedPrice:1,maxAmountToman:null,startAt:new Date().toISOString(),endAt:new Date(Date.now()+60000).toISOString(),intervalMinutes:1,cooldownMinutes:1});db.addEvent(monitor.id,'active',{state:'active'},null,true);assert.equal(db.recentEvents().length,1);db.deleteMonitor(monitor.id);assert.equal(db.recentEvents().length,0);db.close();});

test('updates and bulk deletes legacy and v2 monitoring without deleting archive',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bourse-edit-')),db=openDatabase(path.join(dir,'x.db')),input={title:'اول',symbol:'فولاد',inputMode:'builder',sourceText:'',expression:{type:'rule',field:'lastPrice',operator:'gt',value:1},actionType:'BUY',quantity:1,proposedPrice:1,maxAmountToman:null,startAt:new Date().toISOString(),endAt:new Date(Date.now()+60000).toISOString(),intervalMinutes:1,cooldownMinutes:1},monitor=db.createMonitor(input);assert.equal(db.updateMonitor(monitor.id,{...input,title:'ویرایش'}).title,'ویرایش');const archived=db.createMonitor(input);db.updateMonitorStatus(archived.id,'completed');const rule=db.createRuleV2({ruleId:'R',symbol:'فولاد',name:'قاعده',scope:'SYMBOL',severity:'WATCH',expression:{type:'condition',name:'PRICE_ABOVE',params:{value:1}},action:'ALERT',cooldownMinutes:1,intervalMinutes:1});assert.equal(db.updateRuleV2(rule.id,{...rule,name:'قاعده جدید',enabled:true}).name,'قاعده جدید');const removed=db.bulkDeleteMonitoring([],true);assert.equal(removed.total,2);assert.equal(db.listMonitors({archive:true}).length,1);assert.equal(db.listRulesV2().length,0);db.close();});
