import test from 'node:test';
import assert from 'node:assert/strict';
import {buildIndicatorAnalysis,detectConsolidation} from '../src/indicator-engine.js';

const basePattern=bars=>{const prior=Array.from({length:40},(_,i)=>({date:String(i),open:100+i*.7,high:104+i*.7,low:96+i*.7,close:100+i*.7,volume:1000})),base=Array.from({length:bars},(_,i)=>({date:`b${i}`,open:128,high:129+(i%2)*.1,low:127-(i%3)*.05,close:128+(i%2)*.15,volume:900}));return {candles:[...prior,...base],atr:Array(40).fill(5).concat(Array(bars).fill(1.2)),bbw:Array(40).fill(.3).concat(Array(bars).fill(.08))};};
test('detects clear bases with different real lengths',()=>{const six=basePattern(6),ten=basePattern(10),a=detectConsolidation(six.candles,six.atr,six.bbw,{ema50:120,structureValid:true,bbwPercentile:10}),b=detectConsolidation(ten.candles,ten.atr,ten.bbw,{ema50:120,structureValid:true,bbwPercentile:10});assert.equal(a.recent_consolidation,true);assert.equal(b.recent_consolidation,true);assert.equal(a.consolidation_bars>=5&&a.consolidation_bars<=8,true);assert.equal(b.consolidation_bars>=8&&b.consolidation_bars<=14,true);assert.notEqual(a.consolidation_bars,b.consolidation_bars);});
test('strong expanding trend is not consolidation but keeps debug candidate',()=>{const candles=Array.from({length:50},(_,i)=>({date:String(i),open:100+i*3,high:104+i*3,low:98+i*3,close:103+i*3,volume:1000})),result=detectConsolidation(candles,Array(50).fill(4),Array.from({length:50},(_,i)=>.1+i*.01),{ema50:100,structureValid:true,bbwPercentile:80});assert.equal(result.recent_consolidation,false);assert.equal(result.consolidation_bars>0,true);assert.equal(result.consolidation_best_window>0,true);});
test('structural breakdown prevents a tight range from qualifying',()=>{const data=basePattern(10);data.candles.at(-1).open=128;data.candles.at(-1).high=128;data.candles.at(-1).low=116;data.candles.at(-1).close=117;const result=detectConsolidation(data.candles,data.atr,data.bbw,{ema50:120,structureValid:false,bbwPercentile:10});assert.equal(result.recent_consolidation,false);assert.equal(result.no_structural_break,false);});
test('missing BBW or ATR uses available component normalization',()=>{const data=basePattern(10),withoutBbw=detectConsolidation(data.candles,data.atr,[],{ema50:120,structureValid:true}),withoutAtr=detectConsolidation(data.candles,[],data.bbw,{ema50:120,structureValid:true,bbwPercentile:10});assert.equal(withoutBbw.recent_consolidation,true);assert.equal(withoutAtr.recent_consolidation,true);assert.equal(withoutBbw.consolidation_missing_components.includes('BBW'),true);assert.equal(withoutAtr.consolidation_missing_components.includes('ATR'),true);});
test('insufficient consolidation history is graceful',()=>{const result=detectConsolidation(basePattern(2).candles.slice(-7));assert.equal(result.recent_consolidation,false);assert.equal(result.consolidation_bars,0);});

const candles=Array.from({length:120},(_,index)=>{const close=1000+index*5+Math.sin(index/4)*20;return {date:`1405-${String(Math.floor(index/28)+1).padStart(2,'0')}-${String(index%28+1).padStart(2,'0')}`,open:close-3,high:close+12,low:close-14,close,volume:100000+index*1000};});

test('builds the requested indicator context from cached candles and one live candle',()=>{const analysis=buildIndicatorAnalysis(candles,{date:'1405-07-03',lastPrice:1640,closePrice:1635,openPrice:1620,dayHigh:1650,dayLow:1610,volume:350000,tradeValue:500000000,tradeCount:900,buyVolumeReal:220000,buyCountReal:20,sellVolumeReal:120000,sellCountReal:20,buyerPower:220/120,hasBuyerPowerData:true});assert.equal(analysis.valid,true);for(const key of ['ema20','ema50','rsi14','macd_line','macd_signal','macd_hist','mfi14','obv','atr14','bbw','volume_sma20','volume_ratio_20','max_gain_40_pct','recent_correction_pct','range_compression_10_ratio','tech_recovery_score'])assert.equal(Number.isFinite(analysis.context[key]),true,key);assert.equal(analysis.context.buyer_power>1.8,true);assert.equal(analysis.rows.length,14);});

test('reports insufficient history without inventing values',()=>{const analysis=buildIndicatorAnalysis(candles.slice(0,10));assert.equal(analysis.valid,false);assert.match(analysis.reason,/۵۰ کندل/);assert.equal(analysis.context.ema50,null);});
