import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {openDatabase} from '../src/db.js';
import {evaluateCondition,evaluateRuleExpression,normalizeRuleExpressionV2,RuleEngineV2,validateRuleExpressionV2} from '../src/rule-engine-v2.js';

test('evaluates MACD recovery and a confirmed breakout',()=>{const context={current:{price:3910,volume_ratio_20:1.8,buyer_power:1.4,macd_hist:-20,macd_hist_prev1:-60,macd_hist_prev2:-100},previous:{price:3880}};assert.equal(evaluateCondition({name:'MACD_RECOVERY_EARLY'},context).state,'active');const expression={type:'group',logic:'AND',children:[{type:'condition',name:'BREAKOUT_CONFIRMED',params:{level:3900,volume_ratio:1.5,buyer_power:1.2}},{type:'condition',name:'MACD_RECOVERY_EARLY'}]};assert.equal(evaluateRuleExpression(expression,context).state,'active');});

test('evaluates numeric closing-price limits independently from the last price',()=>{const context={current:{price:7200,close:6900},previous:{price:6800,close:7000}};assert.equal(evaluateCondition({name:'CLOSE_AT_OR_BELOW',params:{value:6900}},context).state,'active');assert.equal(evaluateCondition({name:'CLOSE_ABOVE',params:{value:6700}},context).state,'active');assert.equal(evaluateCondition({name:'PRICE_BELOW',params:{value:6900}},context).state,'inactive');});

test('normalizes the compact JSON rule format used by imports',()=>{const expression=normalizeRuleExpressionV2({op:'AND',conditions:[{type:'PRICE_CROSS_ABOVE',value:3900},{type:'VOLUME_RATIO_ABOVE',value:1.5}]});validateRuleExpressionV2(expression);assert.deepEqual(expression,{type:'group',logic:'AND',children:[{type:'condition',name:'PRICE_CROSS_ABOVE',params:{value:3900}},{type:'condition',name:'VOLUME_RATIO_ABOVE',params:{value:1.5}}]});});

test('creates the versioned schema and feeds multiple rules from one market snapshot',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rule-v2-')),db=openDatabase(path.join(dir,'db.sqlite'));db.createRuleV2({ruleId:'R1',symbol:'بنیرو',name:'قیمت',scope:'SYMBOL',severity:'BUY',expression:{type:'condition',name:'PRICE_ABOVE',params:{value:3900}},action:'BUY_ALERT'});db.createRuleV2({ruleId:'R2',symbol:'بنیرو',name:'قدرت',scope:'SYMBOL',severity:'WATCH',expression:{type:'condition',name:'BUYER_POWER_ABOVE',params:{value:1.2}},action:'ALERT'});let calls=0;const marketData={async marketRows(){calls++;return[{symbol:'بنیرو',lastPrice:4000,changePct:2,buyerPower:1.4,tradeValue:1_000_000,buyVolumeReal:20,sellVolumeReal:10,closePrice:3990,name:'بنیرو'}];},async ruleContext(symbol,row,market){return{current:{price:row.lastPrice,buyer_power:row.buyerPower},previous:{price:3800,buyer_power:1},liveHistory:[],portfolio:null,market};}};const runtime={telegramTargets(){return[];}},engine=new RuleEngineV2({},db,marketData,runtime),output=await engine.run();assert.equal(output.rules,2);assert.equal(calls,1);assert.equal(output.results.every(x=>x.state==='active'),true);assert.equal(db.listRulesV2().length,2);db.close();});

test('suppresses v2 sell alerts until the symbol exists in the portfolio',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'portfolio-sell-')),db=openDatabase(path.join(dir,'db.sqlite'));db.createRuleV2({ruleId:'SELL',symbol:'فولاد',name:'فروش',scope:'SYMBOL',severity:'SELL',expression:{type:'condition',name:'PRICE_ABOVE',params:{value:1}},action:'PARTIAL_PROFIT'});const row={symbol:'فولاد',name:'فولاد',lastPrice:3000,closePrice:3000,changePct:1,buyerPower:1,buyVolumeReal:1,sellVolumeReal:1},marketData={async marketRows(){return[row];},async ruleContext(symbol,current,market){const portfolio=db.portfolioPosition(symbol);return{current:{price:current.lastPrice},previous:{price:2900},liveHistory:[],portfolio,market};}},engine=new RuleEngineV2({},db,marketData,{telegramTargets(){return[];}});let output=await engine.run();assert.equal(output.results[0].state,'insufficient');db.savePortfolioPosition({symbol:'فولاد',quantity:1000,avgPrice:2500});db.raw.prepare("UPDATE rules_v2 SET next_run_at=NULL WHERE rule_id='SELL'").run();output=await engine.run();assert.equal(output.results[0].state,'active');db.close();});

test('sell alert can use the current portfolio quantity and shows closing price',()=>{const engine=new RuleEngineV2({},null,null,null),text=engine.formatAlert({symbol:'دکپسول',name:'خروج',severity:'EXIT',action:'EXIT_ALERT',actionParams:{quantityMode:'portfolio'}},{current:{price:168000,close:167500},portfolio:{quantity:1137}},{state:'active',description:'قیمت پایانی',children:[]});assert.match(text,/۱٬۱۳۷ سهم/);assert.match(text,/۱۶۷٬۵۰۰ ریال/);});

test('final-close rules are excluded from intraday runs and use a forced final snapshot',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'final-close-')),db=openDatabase(path.join(dir,'db.sqlite')),expression={type:'condition',name:'CLOSE_AT_OR_BELOW',params:{value:100}};db.createRuleV2({ruleId:'LIVE',symbol:'الف',name:'عادی',scope:'SYMBOL',severity:'WATCH',expression,action:'ALERT'});db.createRuleV2({ruleId:'CLOSE',symbol:'الف',name:'پایانی',scope:'PORTFOLIO',severity:'EXIT',expression,action:'EXIT_ALERT',actionParams:{finalCloseOnly:true}});db.savePortfolioPosition({symbol:'الف',quantity:10,avgPrice:90});const forceCalls=[],row={symbol:'الف',name:'الف',lastPrice:95,closePrice:95,changePct:0,buyerPower:1,buyVolumeReal:1,sellVolumeReal:1},marketData={async marketRows(options={}){forceCalls.push(Boolean(options.force));return[row];},async ruleContext(symbol,current,market){return{current:{price:current.lastPrice,close:current.closePrice},previous:{},liveHistory:[],portfolio:db.portfolioPosition(symbol),market};}},engine=new RuleEngineV2({},db,marketData,{telegramTargets(){return[];}});let output=await engine.run();assert.equal(output.rules,1);assert.equal(output.results[0].ruleId,'LIVE');output=await engine.run({onlyFinalClose:true,forceMarketData:true});assert.equal(output.rules,1);assert.equal(output.results[0].ruleId,'CLOSE');assert.deepEqual(forceCalls,[false,true]);db.close();});

test('market risk-off downgrades buys one level and never changes exit severity',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'risk-off-')),db=openDatabase(path.join(dir,'db.sqlite')),leaf={type:'condition',name:'PRICE_ABOVE',params:{value:1}};db.createRuleV2({ruleId:'BUY',symbol:'الف',name:'خرید',scope:'SYMBOL',severity:'BUY',expression:leaf,action:'BUY_ALERT'});db.createRuleV2({ruleId:'STRONG',symbol:'الف',name:'خرید قوی',scope:'SYMBOL',severity:'STRONG_BUY',expression:leaf,action:'BUY_ALERT'});db.createRuleV2({ruleId:'EXIT',symbol:'الف',name:'خروج',scope:'SYMBOL',severity:'EXIT',expression:leaf,action:'EXIT_ALERT'});db.createRuleV2({ruleId:'MARKET',name:'ریسک بازار',scope:'MARKET',severity:'WARNING',expression:{type:'condition',name:'MARKET_RISK_OFF',params:{}},action:'ALERT'});const rows=[{symbol:'الف',name:'الف',lastPrice:10,closePrice:10,changePct:-2,buyerPower:.5,buyVolumeReal:1,sellVolumeReal:2},{symbol:'ب',name:'ب',lastPrice:10,closePrice:10,changePct:-1,buyerPower:.6,buyVolumeReal:1,sellVolumeReal:2}];const marketData={async marketRows(){return rows;},async marketIndex(){return{equalWeight:900,equalWeightChange:-100,index:900,indexChange:-100};},async ruleContext(symbol,row,market){return{current:{price:row.lastPrice},previous:{price:0},liveHistory:[],portfolio:null,market};}},engine=new RuleEngineV2({},db,marketData,{telegramTargets(){return[];}}),output=await engine.run(),byId=Object.fromEntries(output.results.map(x=>[x.ruleId,x]));assert.equal(output.riskOff,true);assert.equal(byId.BUY.effectiveSeverity,'WATCH');assert.equal(byId.STRONG.effectiveSeverity,'BUY');assert.equal(byId.EXIT.effectiveSeverity,'EXIT');db.close();});
